export const FETCH_ALL_RESTORENT = "FETCH_ALL_RESTORENT";
export const FETCH_ALL_FOOD = "FETCH_ALL_FOOD";
export const FETCH_ALL_DRINK = "FETCH_ALL_DRINK";
export const POST_USERS_DATA = "POST_USERS_DATA";
export const SINGLE_USERS_DATA = "SINGLE_USERS_DATA";
export const SINGLE_USERS_SET = "SINGLE_USERS_SET";